baseURL = 'https://kevintraver.com/'
languageCode = 'en-us'
title = 'Kevin Traver'

defaultContentLanguage = "en"

copyright = "2023"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "Kevin Traver"

links = [
  { mastodon = "https://mastodon.social/@kevintraver" },
  { github = "https://github.com/kevintraver" },
  { instagram = "https://instagram.com/kevintraver" },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
